name: LLVM

on:
    workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: ubuntu-22.04, platform: x64, cxx: g++, cc: gcc }

    runs-on: ubuntu-20.04
    container:
      image: 'ghcr.io/hxbb00/ubuntu1604:main'
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}

    env:
      CC: ${{ matrix.config.cc }}
      CXX: ${{ matrix.config.cxx }}
      PLATFORM: ${{ matrix.config.platform }}
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    steps:
      - uses: actions/checkout@v3
      - uses: lukka/get-cmake@latest

      - name: Clone LLVM
        shell: bash
        run: build/build.sh clone_llvm
          
      - name: Build LLVM
        shell: bash
        run: build/build.sh build_llvm -platform $PLATFORM

      - name: Package LLVM
        shell: bash
        run: build/build.sh package_llvm -platform $PLATFORM

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: llvm
          path: build/llvm/llvm-*-*.*